import Link from 'next/link'
import { ArrowLeft, ArrowUpRight, Check } from 'lucide-react'
import { InnerFooter, InnerHeader } from '@/components/inner-shell'
import { ProjectCard, ProjectHighlights, ProjectMeta } from '@/components/project-card'
import { ProjectGallery } from '@/components/project-gallery'
import { getProject, getRelatedProjects, projects } from '@/lib/projects'
import { notFound } from 'next/navigation'
export function generateStaticParams() { return projects.map((project) => ({ slug: project.slug })) }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const project = getProject((await params).slug); return { title: project ? `${project.title} | OM SUNBUILD` : 'Project | OM SUNBUILD', description: project?.description } }
export default async function ProjectDetail({ params }: { params: Promise<{ slug: string }> }) { const project = getProject((await params).slug); if (!project) notFound(); const related = getRelatedProjects(project); return <main><InnerHeader/><div className="detail-page"><nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/projects">Our work</Link><span>/</span><strong>{project.title}</strong></nav><section className="detail-hero"><img src={project.coverImage} alt={project.images[0]?.alt ?? project.title}/><div><p className="eyebrow light">{project.type} {project.location ? `· ${project.location}` : ''}</p><h1>{project.title}</h1></div></section><section className="detail-overview"><div><p className="eyebrow">PROJECT OVERVIEW</p><h2>Thoughtful work.<br/><em>Built for the site.</em></h2><p className="body-copy">{project.description}</p><div className="detail-actions"><Link className="button button-green" href="/#contact">Enquire now <ArrowUpRight size={16}/></Link><a className="text-link dark" href="tel:+919109838902">Call us <ArrowUpRight size={15}/></a></div></div><ProjectMeta project={project}/></section><section className="section detail-gallery-section"><div className="section-heading"><div><p className="eyebrow">INSTALLATION GALLERY</p><h2>See the<br/><em>details.</em></h2></div><p className="heading-intro">A visual record of the work. Select an image to move through the installation.</p></div><ProjectGallery project={project}/></section><section className="detail-installation"><div><p className="eyebrow light">INSTALLATION DETAILS</p><h2>What went<br/><em>into it.</em></h2></div><div className="detail-list">{project.installationDetails.map((detail, i) => <div key={detail}><span>0{i + 1}</span><p>{detail}</p><Check size={17}/></div>)}</div></section><section className="section highlights-section"><p className="eyebrow">PROJECT HIGHLIGHTS</p><ProjectHighlights highlights={project.highlights}/></section><section className="section related-projects"><div className="section-heading"><div><p className="eyebrow">KEEP EXPLORING</p><h2>Related<br/><em>projects.</em></h2></div><Link className="text-link dark" href="/projects">View all work <ArrowUpRight size={16}/></Link></div><div className="portfolio-grid related-grid">{related.map((item) => <ProjectCard project={item} key={item.slug}/>)}</div></section></div><InnerFooter/></main> }
